spring:
  application:
    name: document-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      username: mongodb
      password: 2003
      database: stacknote

  #Resource server configuration
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.jelay.site/realms/stack-notes
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

# Keycloak configuration
keycloak:
  auth-server-url: https://keycloak.jelay.site/
  realm: stack-notes
  credentials:
    client-id: stack-notes-client
    secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
    provider: secret

# connect with eureka server
eureka:
  client:
    service-url:
      defaultZone: https://eureka.jelay.site/eureka/  # Adjust for your Eureka server URL
  instance:
    prefer-ip-address: true

# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      realm: stack-notes
      client-id: stack-notes-client
      client-secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
    tags-sorter: alpha

logging:
  level:
    org.springframework.web: debug
server:
  port: 8085
